/**
@file mainpage.h
@author Arnaud Maye   
@brief Doxygen documentation main page
*************************************************************************/

/** @mainpage FMC112-FMC116 software support package (PCI-Ethernet)
*
* @authors Arnaud Maye, 4DSP
*
* @section intro Introduction
* This documentation has been autogenerated using doxygen framework (doxygen, graphviz and the compressed HTMP compiler) 
* from the source code. 
*
* There is one main application and a few helper modules helping controlling various peripheral mounted on the FMC110
* hardware. 
*
* The main application demonstrates how to control and handle the FMC116-FMC112 peripheral on a ML605/KC705 using these helper modules. 
* The software sequence for this application is documented in the main.cpp documentation.
*
* The documentation is arranged as the following hierarchy:
*
* - FMC112-FMC116 Reference Application
* -# main.cpp 
*
* - Interface to the sip_cid firmware star (IP Core).
* -# Libs\CID\Incs\cid.h  (cid)
*
* - Interface to the clock/trigger generation star (IP Core).
* -# Libs\CT_GEN\Incs\ctgen.h (fmc_ct_gen)
*
* - Interface to the FMC116-FMC112 firmware star (IP Core).
* -# Libs\FMC116\Incs\fmc116.h (fmc110)
* -# Libs\FMC116\Incs\fmc116_freqcnt.h (frequency counter)
* -# Libs\FMC116\Incs\fmc116_monitor.h (frequency counter)
* -# Libs\FMC116\Incs\fmc116_ctrl.h (burst size, burst length, arm, disarm, ... )
* -# Libs\FMC116\Incs\fmc116_cpld.h (fans, clock, HDMI signal directions)
* -# Libs\FMC116\Incs\fmc116_clocktree.h (internal/external clock, part id verification)
* -# Libs\FMC116\Incs\fmc116_adc.h (analog to digital converter)
*
* - Interface to the I2C master firmware star (IP Core).
* -# Libs\I2CMASTER\Incs\i2cmaster.h (i2cmaster generic)
* -# Libs\I2CMASTER\Incs\i2cmaster_fmc116.h (i2cmaster code for FMC116-FMC112)
*
* - Interface to the router firmware star (IP Core).
* -# Libs\SXDXROUTER\Incs\sxdxrouter.h (sxdxrouter)
*
*
* - Interface to the sipif module.
* -# Libs\SIPIF\Incs\sipif.h (sipif)
*
*/