/**
@file mainpage.h
@author Arnaud Maye   
@brief Doxygen documentation main page
*************************************************************************/

/** @mainpage FMC204 software support package (XMC/PMC)
*
* @authors Arnaud Maye, 4DSP
*
* @section intro Introduction
* This documentation has been autogenerated using doxygen framework (doxygen, graphviz and the compressed HTMP compiler) 
* from the source code. 
*
* There is one main application and a few helper modules helping controlling various peripheral mounted on the FMC204
* hardware. 
*
* The main application demonstrates how to control and handle the FMC204 peripheral on a ML-605 using these helper modules. 
* The software sequence for this application is documented in the main.cpp documentation.
*
* The documentation is arranged as the following hierarchy:
*
* - FMC204 Reference Application
* -# main.cpp 
*
*
* - Interface to the sip_cid firmware star (IP Core).
* -# Libs\CID\Incs\cid.h  (cid)
*
* - Interface to the FMC204 firmware star (IP Core).
* -# Libs\FMC204\Incs\FMC204.h (FMC204)
* -# Libs\FMC204\Incs\FMC204_freqcnt.h (frequency counter)
* -# Libs\FMC204\Incs\FMC204_dac.h (digital to analog converter)
* -# Libs\FMC204\Incs\FMC204_ctrl.h (burst size, burst length, arm, disarm, ... )
* -# Libs\FMC204\Incs\FMC204_cpld.h (fans, clock, HDMI signal directions)
* -# Libs\FMC204\Incs\FMC204_clocktree.h (internal/external clock, part id verification)
*
* - Interface to the I2C master firmware star (IP Core).
* -# Libs\I2CMASTER\Incs\i2cmaster.h (i2cmaster generic)
* -# Libs\I2CMASTER\Incs\i2cmaster_FMC204.h (i2cmaster code for FMC204)
*
* - Interface to the router firmware star (IP Core).
* -# Libs\SXDXROUTER\Incs\sxdxrouter.h (sxdxrouter)
*
* - Interface to the clock/trigger generation firmware star (IP Core).
* -# Libs\CT_GEN\Incs\ctgen.h (fmc_ct_gen)
*
* - Interface to the hardware (sipif).
* -# Libs\SXDXROUTER\Incs\sipif.h (sxdxrouter)
*
*/